### ISSUE TITLE
Training Phoenix-T

### ISSUE THREAD

**Issue by pallapumohankrishna** [hulianyuyy/CorrNet#68]
[ Fri Feb 28 18:27:28 2025 ] Parameters:
{'work_dir': './work_dir/baseline_res18/', 'config': './configs/baseline.yaml', 'random_fix': True, 'device': '0', 'phase': 'train', 'save_interval': 5, 'random_seed': 0, 'eval_interval': 1, 'print_log': True, 'log_interval': 10000, 'evaluate_tool': 'sclite', 'feeder': 'dataset.dataloader_video.BaseFeeder', 'dataset': 'phoenix2014-T', 'dataset_info': {'dataset_root': './dataset/phoenix2014-T', 'dict_path': './preprocess/phoenix2014-T/gloss_dict.npy', 'evaluation_dir': './evaluation/slr_eval', 'evaluation_prefix': 'phoenix2014-T-groundtruth'}, 'num_worker': 5, 'feeder_args': {'mode': 'test', 'datatype': 'video', 'num_gloss': -1, 'drop_ratio': 1.0, 'frame_interval': 1, 'image_scale': 1.0, 'input_size': 224, 'prefix': './dataset/phoenix2014-T', 'transform_mode': False}, 'model': 'slr_network.SLRModel', 'model_args': {'num_classes': 1116, 'c2d_type': 'resnet18', 'conv_type': 2, 'use_bn': 1, 'share_classifier': True, 'weight_norm': True}, 'load_weights': None, 'load_checkpoints': None, 'decode_mode': 'beam', 'ignore_weights': [], 'batch_size': 2, 'test_batch_size': 2, 'loss_weights': {'SeqCTC': 1.0, 'ConvCTC': 1.0, 'Dist': 25.0}, 'optimizer_args': {'optimizer': 'Adam', 'base_lr': 0.0001, 'step': [20, 35], 'learning_ratio': 1, 'weight_decay': 0.0001, 'start_epoch': 0, 'nesterov': False}, 'num_epoch': 40}

  0%|                                                                                                                                                          | 0/3548 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/media/mohan/mohan/CorrNet/main.py", line 255, in <module>
    processor.start()
  File "/media/mohan/mohan/CorrNet/main.py", line 67, in start
    seq_train(self.data_loader['train'], self.model, self.optimizer,
  File "/media/mohan/mohan/CorrNet/seq_scripts.py", line 28, in seq_train
    loss = model.criterion_calculation(ret_dict, label, label_lgt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mohan/mohan/CorrNet/slr_network.py", line 124, in criterion_calculation
    label_lgt.cpu().int()).mean()
                           ^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

![Image](https://github.com/user-attachments/assets/c30f487d-7ca9-4e6e-a471-bda8925fca2a)

**Comment by mohankrishna12** [comment]
![Image](https://github.com/user-attachments/assets/cfa61842-47ee-4fc5-8aa6-356cc5f8de85)

I have installed ctcdecode as follows: 

git clone --recursive https://github.com/Sushmitha-Deva/ctcdecode.git cd ctcdecode && pip install .  

this is the only difference from your repo. Does it effects the training? Getting the attached error.

**Comment by mohankrishna12** [comment]
[ Fri Feb 28 20:01:54 2025 ] Parameters:
{'work_dir': './work_dir/baseline_res18/', 'config': './configs/baseline.yaml', 'random_fix': True, 'device': '0', 'phase': 'train', 'save_interval': 5, 'random_seed': 0, 'eval_interval': 1, 'print_log': True, 'log_interval': 10000, 'evaluate_tool': 'sclite', 'feeder': 'dataset.dataloader_video.BaseFeeder', 'dataset': 'phoenix2014-T', 'dataset_info': {'dataset_root': './dataset/phoenix2014-T', 'dict_path': './preprocess/phoenix2014-T/gloss_dict.npy', 'evaluation_dir': './evaluation/slr_eval', 'evaluation_prefix': 'phoenix2014-T-groundtruth'}, 'num_worker': 5, 'feeder_args': {'mode': 'test', 'datatype': 'video', 'num_gloss': -1, 'drop_ratio': 1.0, 'frame_interval': 1, 'image_scale': 1.0, 'input_size': 224, 'prefix': './dataset/phoenix2014-T', 'transform_mode': False}, 'model': 'slr_network.SLRModel', 'model_args': {'num_classes': 1116, 'c2d_type': 'resnet18', 'conv_type': 2, 'use_bn': 1, 'share_classifier': True, 'weight_norm': True}, 'load_weights': None, 'load_checkpoints': None, 'decode_mode': 'beam', 'ignore_weights': [], 'batch_size': 1, 'test_batch_size': 1, 'loss_weights': {'SeqCTC': 1.0, 'ConvCTC': 1.0, 'Dist': 25.0}, 'optimizer_args': {'optimizer': 'Adam', 'base_lr': 0.0001, 'step': [20, 35], 'learning_ratio': 1, 'weight_decay': 0.0001, 'start_epoch': 0, 'nesterov': False}, 'num_epoch': 40}

  0%|                                                                                                                                                          | 0/7096 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/media/mohan/mohan/CorrNet/main.py", line 255, in <module>
    processor.start()
  File "/media/mohan/mohan/CorrNet/main.py", line 67, in start
    seq_train(self.data_loader['train'], self.model, self.optimizer,
  File "/media/mohan/mohan/CorrNet/seq_scripts.py", line 28, in seq_train
    loss = model.criterion_calculation(ret_dict, label, label_lgt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mohan/mohan/CorrNet/slr_network.py", line 122, in criterion_calculation
    loss += weight * self.loss['CTCLoss'](ret_dict["sequence_logits"].log_softmax(-1),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/nn/modules/loss.py", line 1980, in forward
    return F.ctc_loss(
           ^^^^^^^^^^^
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/nn/functional.py", line 3069, in ctc_loss
    return torch.ctc_loss(
           ^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by hulianyuyy** [comment]
The code works for me, but you may try to remove `.cpu()` in line 122 and 123 to see if it works. Besides, what's your torch version? I used torch 2.0.1 or torch 2.1.2.

**Comment by mohankrishna12** [comment]
import torch

print(“Torch version:”, torch.version)
Torch version: 2.5.1+cu121
print(“CUDA version:”, torch.version.cuda)
CUDA version: 12.1
print(“cuDNN version:”, torch.backends.cudnn.version())
cuDNN version: 90701
exit(0
… )

**Comment by hulianyuyy** [comment]
Thx. Maybe you could try removing `.cpu()` in line 122 and 123 to see if it works, or degrade torch version to 2.1.2 or 2.0.1. Besides, do you have successfully conducted the experiments on phoenix2014 dataset?

**Comment by mohankrishna12** [comment]
No, I am experimenting on Phoenix 2014 -T as of now.

**Comment by mohankrishna12** [comment]
Hi @hulianyuyy ,
can you please tell me your configurations which you had implemented this on (else successfully trained latest configurations):

cuda toolkit, cudnn, pytorch, gcc/g++ versions?

at my end, i am using ubuntu 24, nvidia drivers 550.120,  
tried with cuda 12.1 + torch 2.5.1 but got the above mentioned error. 

**Later I tried cuda 12.1 + torch 2.2.2 but got the below error:** 

1VariantPackEP11CUstream_stRNS0_18LayerNormFwdParamsERKNS1_20NormForwardOperationEmb, version libcudnn_cnn_infer.so.8
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/lib64/libcudnn_cnn_train.so.8: undefined symbol: _ZN5cudnn3cnn34layerNormFwd_execute_internal_implERKNS_7backend11VariantPackEP11CUstream_stRNS0_18LayerNormFwdParamsERKNS1_20NormForwardOperationEmb, version libcudnn_cnn_infer.so.8
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/lib64/libcudnn_cnn_train.so.8: undefined symbol: _ZN5cudnn3cnn34layerNormFwd_execute_internal_implERKNS_7backend11VariantPackEP11CUstream_stRNS0_18LayerNormFwdParamsERKNS1_20NormForwardOperationEmb, version libcudnn_cnn_infer.so.8
  0%|                                                                                                                                                          | 0/3548 [00:27<?, ?it/s]
Traceback (most recent call last):
  File "/media/mohan/mohan/CorrNet/main.py", line 255, in <module>
    processor.start()
  File "/media/mohan/mohan/CorrNet/main.py", line 67, in start
    seq_train(self.data_loader['train'], self.model, self.optimizer,
  File "/media/mohan/mohan/CorrNet/seq_scripts.py", line 35, in seq_train
    scaler.scale(loss).backward()
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: GET was unable to find an engine to execute this computation
 

So, If you tell me on what configurations, you are able to train,test at recent times. 

Thanks

**Comment by hulianyuyy** [comment]
I use python=3.9.7, cuda=12.1, cudnn=8.2, nvidia driver 530.30, pytorch=2.0.1, gcc=9.4.0, ubuntu 18.04.

**Comment by mohankrishna12** [comment]
Are these configs same with corrnet plus aslo?

**Comment by hulianyuyy** [comment]
Yes, they are.

**Comment by mohankrishna12** [comment]
### I use python=3.12.9, cuda=12.1, cudnn=8.9, nvidia driver 550.120, pytorch=2.5.1, gcc=11.4.0, ubuntu 24.

[ Sat Mar  1 19:08:40 2025 ] Parameters:
{'work_dir': './work_dir/baseline_res18/', 'config': './configs/baseline.yaml', 'random_fix': True, 'device': '0', 'phase': 'train', 'save_interval': 5, 'random_seed': 0, 'eval_interval': 1, 'print_log': True, 'log_interval': 10000, 'evaluate_tool': 'sclite', 'feeder': 'dataset.dataloader_video.BaseFeeder', 'dataset': 'phoenix2014-T', 'dataset_info': {'dataset_root': './dataset/phoenix2014-T', 'dict_path': './preprocess/phoenix2014-T/gloss_dict.npy', 'evaluation_dir': './evaluation/slr_eval', 'evaluation_prefix': 'phoenix2014-T-groundtruth'}, 'num_worker': 10, 'feeder_args': {'mode': 'test', 'datatype': 'video', 'num_gloss': -1, 'drop_ratio': 1.0, 'frame_interval': 1, 'image_scale': 1.0, 'input_size': 224, 'prefix': './dataset/phoenix2014-T', 'transform_mode': False}, 'model': 'slr_network.SLRModel', 'model_args': {'num_classes': 1116, 'c2d_type': 'resnet18', 'conv_type': 2, 'use_bn': 1, 'share_classifier': True, 'weight_norm': True}, 'load_weights': None, 'load_checkpoints': None, 'decode_mode': 'beam', 'ignore_weights': [], 'batch_size': 2, 'test_batch_size': 2, 'loss_weights': {'SeqCTC': 1.0, 'ConvCTC': 1.0, 'Dist': 25.0}, 'optimizer_args': {'optimizer': 'Adam', 'base_lr': 0.0001, 'step': [20, 35], 'learning_ratio': 1, 'weight_decay': 0.0001, 'start_epoch': 0, 'nesterov': False}, 'num_epoch': 1}

  0%|                                                                                                                                                          | 0/3548 [00:28<?, ?it/s]
Traceback (most recent call last):
  File "/media/mohan/mohan/CorrNet/main.py", line 255, in <module>
    processor.start()
  File "/media/mohan/mohan/CorrNet/main.py", line 67, in start
    seq_train(self.data_loader['train'], self.model, self.optimizer,
  File "/media/mohan/mohan/CorrNet/seq_scripts.py", line 28, in seq_train
    loss = model.criterion_calculation(ret_dict, label, label_lgt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mohan/mohan/CorrNet/slr_network.py", line 122, in criterion_calculation
    loss += weight * self.loss['CTCLoss'](ret_dict["sequence_logits"].log_softmax(-1),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/nn/modules/loss.py", line 1980, in forward
    return F.ctc_loss(
           ^^^^^^^^^^^
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/nn/functional.py", line 3069, in ctc_loss
    return torch.ctc_loss(
           ^^^^^^^^^^^^^^^
### RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by mohankrishna12** [comment]
/media/mohan/mohan/CorrNet
preprocess.sh ./work_dir/baseline_res18/output-hypothesis-dev-conv.ctm ./work_dir/baseline_res18/tmp.ctm ./work_dir/baseline_res18/tmp2.ctm
Sat Mar 1 09:51:02 PM IST 2025
Preprocess Finished.
sh: 1: ./software/sclite: not found
/bin/sh: 1: ./software/sclite: not found
Unexpected error: <class 'IndexError'>
Traceback (most recent call last):
  File "/media/mohan/mohan/CorrNet/main.py", line 255, in <module>
    processor.start()
  File "/media/mohan/mohan/CorrNet/main.py", line 70, in start
    dev_wer = seq_eval(self.arg, self.data_loader['dev'], self.model, self.device,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/mohan/mohan/CorrNet/seq_scripts.py", line 95, in seq_eval
    del conv_ret
        ^^^^^^^^
**### UnboundLocalError: cannot access local variable 'conv_ret' where it is not associated with a value**



![Image](https://github.com/user-attachments/assets/895d18e3-80b3-413a-9a57-46ba7a096a93)

**Comment by hulianyuyy** [comment]
You can freely comment line 95 `del conv_ret` in `CorrNet/seq_scripts.py`.

**Comment by mohankrishna12** [comment]
Hi @hulianyuyy 


/media/mohan/mohan/CorrNet
preprocess.sh ./work_dir/baseline_res18/output-hypothesis-dev-conv.ctm ./work_dir/baseline_res18/tmp.ctm ./work_dir/baseline_res18/tmp2.ctm
Tue Mar 4 04:14:47 PM IST 2025
Preprocess Finished.
### sh: 1: ./software/sclite: not found
/bin/sh: 1: ./software/sclite: not found
Unexpected error: <class 'IndexError'>
**[ Tue Mar  4 16:14:47 2025 ] Epoch 17, dev  100.00%
[ Tue Mar  4 16:14:47 2025 ] Dev WER: 100.00%
[ Tue Mar  4 16:14:47 2025 ] Best_dev: 100.00, Epoch : 0
[ Tue Mar  4 16:14:47 2025 ] Epoch 17 costs 78 mins 22 seconds**


WER is 100% in every epoch and not reducing. Due to sclite, but i have installed sclite and created softlink as well .

![Image](https://github.com/user-attachments/assets/f1f8a6eb-e720-42a0-a939-5d82c42a5d24)

**Comment by hulianyuyy** [comment]
This is caused by that sclite is not correctly linked. Could you provide your command to create the soft link?

**Comment by mohankrishna12** [comment]
mkdir ./software ln -s /media/mohan/mohan/CorrNet/kaldi/tools/sctk-2.4.10/bin/sclite ./software/sclite

**Comment by hulianyuyy** [comment]
It seems that there doesn't exist a `sctk-2.4.10` in `tools` dir.

**Comment by hulianyuyy** [comment]
You could change sctk-2.4.10 with sctk.

**Comment by mohankrishna12** [comment]
![Image](https://github.com/user-attachments/assets/14c15e17-2160-439b-b146-97068dd2aceb)

Its training Properly Now, 
Thank You @hulianyuyy

**Comment by hulianyuyy** [comment]
You are welcome. I also want to remind you that you should use batch size=2 instead of 1 as batchsize=1 would leads to much worse results than batch size=2 than you expected.

**Comment by mohankrishna12** [comment]
@hulianyuyy 
If I use batch size =2 then its leading to Cuda out of memory !
Do you think will it work if I try again on NVIDIA RTX A5000 with 24 GB RAM.? 
Between what are the total parameters of the model? 
#FLOPS which you had worked on?

**Comment by mohankrishna12** [comment]
### Hi @hulianyuyy  I have trained with batch size = 1, but [ Fri Mar  7 02:51:44 2025 ] Best_dev: 31.60, Epoch : 21
![Image](https://github.com/user-attachments/assets/0dc6f32d-1238-4092-a7d5-78cc61267dc0)

Also the visualizations are coming as below. 
![Image](https://github.com/user-attachments/assets/97ae4002-40ec-4f03-96b7-aa36fa81eb8f)

### (corrnet) mohan@debanga-Precision-7820-Tower:/media/mohan/mohan/CorrNet$ python test_one_video.py --model_path ./work_dir/baseline_res18/_best_model.pt --video_path /media/mohan/mohan/phoenix-2014-T.v3/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px/test/02June_2010_Wednesday_heute-6789 --device 0
/media/mohan/mohan/CorrNet/test_one_video.py:111: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(args.model_path)['model_state_dict']
Traceback (most recent call last):
  File "/media/mohan/mohan/CorrNet/test_one_video.py", line 113, in <module>
    model.load_state_dict(state_dict, strict=True)
  File "/media/mohan/anaconda3/envs/corrnet/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    **raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for SLRModel:
        size mismatch for conv1d.fc.weight: copying a param with shape torch.Size([1024, 1116]) from checkpoint, the shape in current model is torch.Size([1024, 1296]).
        size mismatch for classifier.weight: copying a param with shape torch.Size([1024, 1116]) from checkpoint, the shape in current model is torch.Size([1024, 1296]).
(corrnet) mohan@debanga-Precision-7820-Tower:/media/mohan/mohan/CorrNet$**

**Comment by hulianyuyy** [comment]
Change line 50 in `test_one_video.py` to `phoenix2014-T` could help you.

**Comment by hulianyuyy** [comment]
If you want to train with batchsize=2 normally, you should get a larger GPU, or try to use fewer CorrNet blocks (this may degrade the performance). Num classes argument is dynamically decided in the main.py according to your dataset, which is not influenced by the baseline.yaml.

**Comment by hulianyuyy** [comment]
Currently, this code doesn't support distributed training due to the usage of ctc loss.
